config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'mypages#index'
  resources :users, only: [:index, :edit, :update]
  resources :students, only: [:new, :create, :edit, :update, :destroy] do
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
end

app/views/mypages/_footer.html.haml
.footer
  .footer__box
    .footer__box__info
      %ul
        %li 教室長より
        %li 教室情報
        %li 使い方
    .footer__box__text
      © hokokusho, Inc.

app/views/mypages/_header.html.haml
.header
  .header__logo
    = link_to root_path do
      = image_tag "hokokusho.png", width: "200px", height: "60px"
  .header__bottom
    .header__bottom__user
      = current_user.last_name + current_user.first_name + "でログイン中"
      = link_to edit_user_registration_path(current_user.id) do
        = icon("far", "edit", class: "icon")
    - if current_user.user_status_id == "3"
      .header__bottom__student
        = link_to new_student_path do
          新規生徒作成
    .header__bottom__logout
      = link_to destroy_user_session_path, method: :delete do
        ログアウト

app/views/mypages/index.html.haml
.mypage-wrapper
  = render "header"
  .mypage-main
    - if current_user.user_status_id == "1"
      .mypage-main__student
        - current_user.students.each do |student|
          .mypage-main__student__box
            = link_to student_reports_path(student) do
              .student__container__school
                .student__container__school__subject
                  = student.subject.name
                .student__container__school__grade
                  = "#{student.school.name}#{student.grade.name}年"

    - elsif current_user.user_status_id == "2" 
      .mypage-main__parent
        - current_user.students.each do |student|
          .mypage-main__parent__box
            = link_to student_reports_path(student) do
              .student__container__name
                = student.name
              .student__container__school
                .student__container__school__subject
                  = student.subject.name
                .student__container__school__grade
                  = "#{student.school.name}#{student.grade.name}年"

    - else
      .mypage-main__school
        .mypage-main-school-name
          小学生
        .student-container
          - current_user.students.each do |student|
            - if student.school.id == 1
              .student-container__box.elementary-school
                = link_to student_reports_path(student) do
                  .student-box__name
                    = student.name
                  .student-box__school
                    .student-box__school__grade
                      = "#{student.school.name}#{student.grade.name}年"
                    .student-box__school__subject
                      = student.subject.name
                .student-edit-delete
                  = link_to edit_student_path(student) do
                    = icon("far", "edit", class: "icon")
                  = link_to student_path(student), method: 'delete', data: { confirm: '削除しますか？' } do
                    = icon("fas", "trash-alt", class: "icon")
      .mypage-main__school
        .mypage-main-school-name
          中学生
        .student-container
          - current_user.students.each do |student|
            - if student.school.id == 2
              .student-container__box.junior-high-school
                = link_to student_reports_path(student) do
                  .student-box__name
                    = student.name
                  .student-box__school
                    .student-box__school__grade
                      = "#{student.school.name}#{student.grade.name}年"
                    .student-box__school__subject
                      = student.subject.name
                .student-edit-delete
                  = link_to edit_student_path(student) do
                    = icon("far", "edit", class: "icon")
                  = link_to student_path(student), method: 'delete', data: { confirm: '削除しますか？' } do
                    = icon("fas", "trash-alt", class: "icon")
      .mypage-main__school
        .mypage-main-school-name
          高校生
        .student-container
          - current_user.students.each do |student|
            - if student.school.id == 3
              .student-container__box.high-school
                = link_to student_reports_path(student) do
                  .student-box__name
                    = student.name
                  .student-box__school
                    .student-box__school__grade
                      = "#{student.school.name}#{student.grade.name}年"
                    .student-box__school__subject
                      = student.subject.name
                .student-edit-delete
                  = link_to edit_student_path(student) do
                    = icon("far", "edit", class: "icon")
                  = link_to student_path(student), method: 'delete', data: { confirm: '削除しますか？' } do
                    = icon("fas", "trash-alt", class: "icon")
  = render "footer"