config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'mypages#index'
  resources :users, only: [:index, :edit, :update]
  resources :students, only: [:new, :create, :edit, :update, :destroy] do
    resources :reports, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :student
  belongs_to :user
  has_many :comments

  validates :year, :month, :day, :homework_rate, :teacher, :next_class, presence: true
  validates :unit ,length: { maximum: 30}, presence: true
  validates :content ,length: { maximum: 300}, presence: true
  validates :homework ,length: { maximum: 150}, presence: true

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_student

  def index
    @reports = @student.reports.includes(:user).order("created_at DESC")
    @comment = Comment.new
  end

  def new
    @report = Report.new
    redirect_to root_path unless current_user.user_status_id == "3"
  end

  def create
    @report = @student.reports.new(report_params)
    if @report.save
      redirect_to student_reports_path(@student)
    else
      render :new
    end
  end

  def edit
    @report = Report.find(params[:id])
    redirect_to root_path unless @report.user_id == current_user.id
  end

  def update
    @report = @student.reports.find(params[:id])
    if @report.update(report_params)
      redirect_to student_reports_path(@student)
    else
      redirect_to student_reports_path(@student)
    end
  end

  def destroy
    @report = @student.reports.find(params[:id])
    if (@report.user_id == current_user.id) && @report.destroy
      redirect_to student_reports_path(@student)
    else
      redirect_to student_reports_path(@student)
    end
  end

  private
  def report_params
    params.require(:report).permit(
      :year,
      :month,
      :day,
      :unit,
      :homework_rate,
      :mini_test,
      :mini_test_rate,
      :content,
      :teacher,
      :confirmation,
      :homework,
      :next_class,
    ).merge(user_id: current_user.id)
  end

  def set_student
    @student = Student.find(params[:student_id])
  end
end

app/views/reports/_create-report-btn.html.haml
.create-report-btn
  = link_to new_student_report_path(@student) do
    .create-report-btn__box
      .create-report-btn__box--text
        報告書
        %br
        作成

app/views/reports/edit.html.haml
.new-report-wrapper
  = render 'shared/header-simple'
  = render 'shared/second-header'
  .new-report-main
    = form_for [@student, @report] do |f|
      .new-report-main__container

        .new-report-main__container__left
          .new-report-main__container__left__first
            .new-report-main__container__left__first__date
              .new-report-main__container__left__first__date__ymd
                = f.select :year, [*2020..2021], prompt: "--"
                %span 年
              .new-report-main__container__left__first__date__ymd
                = f.select :month, [*1..12], prompt: "--"
                %span 月
              .new-report-main__container__left__first__date__ymd
                = f.select :day, [*1..31], prompt: "--"
                %span 日
            .new-report-main__container__left__first__teacher
              担当
              .new-report-main__container__left__first__teacher__name
                = f.text_field :teacher, value: current_user.last_name
            .new-report-main__container__left__first__confirmation
              確認
              .new-report-main__container__left__first__confirmation__name
                = f.text_field :confirmation
          .new-report-main__container__left__second
            .new-report-main__container__left__second__unit-name
              単元名：
            .new-report-main__container__left__second__unit-field
              = f.text_field :unit, class: 'unit'
          .new-report-main__container__left__third
            .new-report-main__container__left__third__homework-rate
              宿題実施率
              .new-report-main__container__left__third__homework-rate__text
                = f.select :homework_rate, [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "--"
                %span %
            .new-report-main__container__left__third__mini_test
              .new-report-main__container__left__third__mini_test__name
                小テスト
                .new-report-main__container__left__third__mini_test__name__text
                  = f.text_field :mini_test
              .new-report-main__container__left__third__mini_test__rate
                正答率
                .new-report-main__container__left__third__mini_test__rate__text
                  = f.select :mini_test_rate, [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "--"
                  %span %
          .new-report-main__container__left__fourth
            = f.text_area :content, class: 'content', placeholder: '本日の内容'

        .new-report-main__container__right
          .new-report-main__container__right__first
            宿題
            .new-report-main__container__right__first
              = f.text_area :homework
          .new-report-main__container__right__second
            次回授業
            .new-report-main__container__right__second__next-class
              !=sprintf(f.date_select(:next_class, use_month_numbers: true, date_separator: '%s'),'年','月')+'日'
      
      .new-report-main__submit
        = f.submit '変更', class: 'new-report-main__submit__btn'

  = render "mypages/footer"

app/views/reports/index.html.haml
.report-wrapper
  = render "shared/header-simple"
  = render 'shared/second-header'
  - if current_user.user_status_id == "3"
    = render "create-report-btn"
  .report-main
    - @reports.each do |report|
      .report-main__container

        .report-main__container__left
          .report-main__container__left__first
            .report-main__container__left__first__date
              .report-main__container__left__first__date__ymd
                = "#{report.year}年"
              .report-main__container__left__first__date__ymd
                = "#{report.month}月"
              .report-main__container__left__first__date__ymd
                = "#{report.day}日"
            .report-main__container__left__first__teacher
              担当：
              .report-main__container__left__first__teacher__name
                = report.teacher
            .report-main__container__left__first__confirmation
              確認：
              .report-main__container__left__first__confirmation__name
                = report.confirmation
          .report-main__container__left__second
            .report-main__container__left__second__unit-name
              単元名：
            .report-main__container__left__second__unit-field
              = report.unit
          .report-main__container__left__third
            .report-main__container__left__third__homework-rate
              宿題実施率：
              .report-main__container__left__third__homework-rate__text
                = "#{report.homework_rate}%"
            .report-main__container__left__third__mini_test
              .report-main__container__left__third__mini_test__name
                小テスト：
                .report-main__container__left__third__mini_test__name__text
                  = report.mini_test
              .report-main__container__left__third__mini_test__rate
                正答率：
                .report-main__container__left__third__mini_test__rate__text
                  = "#{report.mini_test_rate}%"
          .report-main__container__left__fourth
            .report-main__container__left__fourth__name
              本日の内容
            .report-main__container__left__fourth__content
              = simple_format(report.content)

        .report-main__container__right
          .report-main__container__right__first
            .report-main__container__right__first__name
              宿題
            .report-main__container__right__first__homework
              = simple_format(report.homework)
          .report-main__container__right__second
            .report-main__container__right__second__next-class
              .report-main__container__right__second__next-class__name
                次回授業
              .report-main__container__right__second__next-class__date
                - next_class = report.next_class.to_s.split("-")
                = "#{next_class[1]}月"
                = "#{next_class[2]}日"
            .report-main__container__right__second__btn
              .report-main__container__right__second__btn__edit
                = link_to edit_student_report_path(@student, report) do
                  編集
              .report-main__container__right__second__btn__delete
                = link_to student_report_path(@student, report), method: 'delete', data: { confirm: '削除しますか？' }  do
                  削除
    
        .comment-wrapper
          .comment-main
            .comment-main__top
              .comment-main__top__title
                ご家庭より
              .comment-main__top__form
                = form_for [@student, report, @comment] do |f|
                  .comment-main__top__form__text
                    = f.text_area :text, class: 'comment-form'
                  .comment-main__top__form__submit
                    = f.submit 'コメントする', class: 'comment-submit-btn'
            .comment-main__bottom
              .comment-main__bottom__title
                コメント一覧
              .comment-main__bottom__box
                - report.comments.each do |comment|
                  .comment-main__bottom__box__text
                    = simple_format(comment.text)
                    = link_to student_report_comment_path(@student, report, comment), method: 'delete', data: { confirm: '削除しますか？' } do
                      = icon("fas", "trash-alt", class: "icon")
              

  = render "mypages/footer"

app/views/reports/new.html.haml
.new-report-wrapper
  = render 'shared/header-simple'
  = render 'shared/second-header'
  .new-report-main
    = form_for [@student, @report] do |f|
      .new-report-main__container

        .new-report-main__container__left
          .new-report-main__container__left__first
            .new-report-main__container__left__first__date
              .new-report-main__container__left__first__date__ymd
                = f.select :year, [*2020..2021], prompt: "--"
                %span 年
              .new-report-main__container__left__first__date__ymd
                = f.select :month, [*1..12], prompt: "--"
                %span 月
              .new-report-main__container__left__first__date__ymd
                = f.select :day, [*1..31], prompt: "--"
                %span 日
            .new-report-main__container__left__first__teacher
              担当
              .new-report-main__container__left__first__teacher__name
                = f.text_field :teacher, value: current_user.last_name
            .new-report-main__container__left__first__confirmation
              確認
              .new-report-main__container__left__first__confirmation__name
                = f.text_field :confirmation
          .new-report-main__container__left__second
            .new-report-main__container__left__second__unit-name
              単元名：
            .new-report-main__container__left__second__unit-field
              = f.text_field :unit, class: 'unit'
          .new-report-main__container__left__third
            .new-report-main__container__left__third__homework-rate
              宿題実施率
              .new-report-main__container__left__third__homework-rate__text
                = f.select :homework_rate, [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "--"
                %span %
            .new-report-main__container__left__third__mini_test
              .new-report-main__container__left__third__mini_test__name
                小テスト
                .new-report-main__container__left__third__mini_test__name__text
                  = f.text_field :mini_test
              .new-report-main__container__left__third__mini_test__rate
                正答率
                .new-report-main__container__left__third__mini_test__rate__text
                  = f.select :mini_test_rate, [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "--"
                  %span %
          .new-report-main__container__left__fourth
            = f.text_area :content, class: 'content', placeholder: '本日の内容'

        .new-report-main__container__right
          .new-report-main__container__right__first
            宿題
            .new-report-main__container__right__first
              = f.text_area :homework
          .new-report-main__container__right__second
            次回授業
            .new-report-main__container__right__second__next-class
              !=sprintf(f.date_select(:next_class, use_month_numbers: true, date_separator: '%s'),'年','月')+'日'
      
      .new-report-main__submit
        = f.submit '作成', class: 'new-report-main__submit__btn'

  = render "mypages/footer"